"""Criando tabelas Users e Addresses

Revision ID: 5614ce368894
Revises: 
Create Date: 2025-02-09 14:22:03.682083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5614ce368894'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_main', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('is_main')

    # ### end Alembic commands ###
