"""Adicionando colunas de endereço ao Users

Revision ID: d46cc3e877c3
Revises: 
Create Date: 2025-02-08 12:55:18.814558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46cc3e877c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('complement', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=120), nullable=False))
        batch_op.drop_column('address')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('complement', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('complement')
        batch_op.drop_column('number')
        batch_op.drop_column('street')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('complement')
        batch_op.drop_column('number')
        batch_op.drop_column('street')

    # ### end Alembic commands ###
